#cloud-config
package_update: true
package_upgrade: true
output: {all: '| tee -a /var/log/cloud-init-output.log'}
packages:
  - build-essential
  - apache2
  - apache2-utils
  - apt-transport-https
  - autoconf
  - automake
  - bat
  - boxes
  - bzip2
  - curl 
  - delta
  - docker-compose
  - flake8
  - fswatch
  - fzf
  - ghostscript
  - git
  - git-lfs
  - glances
  - htop
  - jq
  - libapache2-mod-wsgi 
  - libcairo2-dev
  - libxt-dev
  - manpages-dev
  - net-tools
  - nginx
  - nodejs
  - npm
  - postgresql
  - python3
  - python3-dev
  - python3-pip
  - rsync
  - snapcraft
  - ssl-cert
  - tcsh
  - tree
  - virtualenv
  - wget
  - xrdp
  - zsh
  - imagemagick
snap:
  commands:
    - [ install, emacs, --channel=beta, --classic ]
groups:
  - docker
  - staff
  - www-data
users:
  - default
  - name: mhucka
    shell: /bin/tcsh
    gecos: Mike Hucka
    primary_group: staff
    groups: [ users, staff, adm, sudo, www-data ]
    ssh_import_id:
      - gh:mhucka
    sudo: ALL=(ALL) NOPASSWD:ALL
runcmd:
  - adduser ubuntu docker
  - adduser ubuntu staff
  - adduser ubuntu www-data
