#cloud-config
package_update: true
package_upgrade: true
output: {all: '| tee -a /var/log/cloud-init-output.log'}
packages:
  - build-essential
  - bat
  - bzip2
  - curl 
  - delta
  - git
  - git-lfs
  - glances
  - htop
  - jq
  - manpages-dev
  - net-tools
  - python3
  - python3-dev
  - python3-pip
  - rsync
  - snapcraft
  - ssl-cert
  - tcsh
  - tree
  - virtualenv
  - wget
snap:
  commands:
    - [ install, emacs, --channel=beta, --classic ]
groups:
  - staff
users:
  - default
  - name: mhucka
    shell: /bin/tcsh
    gecos: Mike Hucka
    primary_group: staff
    groups: [ users, staff, adm, sudo ]
    ssh_import_id:
      - gh:mhucka
    sudo: ALL=(ALL) NOPASSWD:ALL
